# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: cd src && make build

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2023.1"
        min-go-version: 1.19
        install-go: true # default is true
        working-directory: ./src/client

    - name: Test
      run: cd src && make test
    
    - name: Build samples
      run: cd samples && make build

    - name: Staticcheck samples
      run: cd samples && make check
